version: "3.5"
services:
  kavanet-controller:
    container_name: kavanet-controller
    build:
      context: .
      dockerfile: Dockerfile
    image: kavanet-controller:latest
    volumes: 
      - "./src:/usr/src/app/src" # copy everything to app inside container
      - "/node_modules" # Ignore node modules
    command: "npm run start:dev"
    ports:
      - 4000:4000
      - 5001:5001
    networks:
      - proxynet

networks:
  proxynet:
    name: kavanet-network
